spring:
  application:
    name: jdbc-spring
  datasource:
    url: jdbc:postgresql://localhost:5432/calorie-tracker
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver